### ISSUE TITLE
[bug] NODE_PATH makes inner dependencies unresolvable

### ISSUE THREAD

**Issue by blake-newman** [knpwrs/vue-node#1]
(This may be a webpack issue, or configuration of vue-node config)

Essentially if you are using NODE_PATH the require paths in output of component are wrong. 

NODE_PATH Inc variable, essentially adds a global root of application acting as a good way to remove `../../` chains to something like `src/component/blah` or `server/api/blah` this enables sort of aliasing in node.js, creating consistency between transpiled code and not transpiled code. 

Essentially what is happening is a require output for a component in vue-node is `src/component/src/component/2`. With context in webpack a normal build resolves fine, but as the dependencies are treated as external then the paths are not correctly managed. 

Im currently unsure where the issue lies, I'll cc @TheLarkInn to see if he has any thoughts. It may be that for node target, paths without `./` are treated as relative but should be considered absolute to the context of webpack config.

**Comment by knpwrs** [comment]
Just spitballing a quick idea, I wonder if we could modify the webpack config to read `NODE_PATH` and use custom resolution logic.

**Comment by nickmessing** [comment]
@knpwrs, check the [PR#2](https://github.com/knpwrs/vue-node/pull/2) when you got some time please.
