### ISSUE TITLE
Should respect existing `resolve.modules` config if it exists

### ISSUE THREAD

**Issue by chrisnicola** [knpwrs/vue-node#10]
vue-node is overwriting `resolve.modules` if there is a `NODE_PATH` value found. This limits configuration options. It would be good if the supplied configuration would be respected.

I am currently using this with Nuxt, Avoriaz and Tape and I have a `lib` folder that I am including as a module folder.

**Comment by knpwrs** [comment]
I'll accept a pull request to fix the issue but please note that this library is pending deprecation. See `README.md` for more info.

**Comment by chrisnicola** [comment]
Yes I saw that. Interestingly I am using Avoriaz, but the guidance for using that still requires `vue-node` to work with Tape. Is there a better approach to handling this that I should be using.

**Comment by chrisnicola** [comment]
So I built this to handle webpacking test scripts in a bit more generic way http://github.com/WealthBar/wprun.

I'll close this now.
