### ISSUE TITLE
Config note for `vue-loader@^12.0`

### ISSUE THREAD

**Issue by yyx990803** [knpwrs/vue-node#9]
In the near future, with the following setup:

- `vue` & `vue-template-compiler` >= 2.4.0
-  `vue-loader` >= 12.1.0
- webpack config with `target: 'node'`

The `*.vue` component will automatically be compiled in "SSR optimization mode" which makes its render function unsable for DOM-based rendering/testing. For this lib to work properly after Vue 2.4 is out, the user will need to turn this off explicitly using a new `vue-loader` option `optimizeSSR: false`. It will probably be at least a month from now but just want to give you a heads up.

**Comment by knpwrs** [comment]
Thanks, @yyx990803. Is that option available now?

**Comment by yyx990803** [comment]
@knpwrs yeah it's already in `vue-loader@12.1.1`.
